export const images = {
  di: {
    still: "/di/distillery-still.webp",
    detail: "/di/di_prom.webp",
    gauge: "/di/distillery-gauge.webp",
    team: "/team.jpeg",
    us: "/us.webp",
  },
  logos: {
    diWhite: "/logos/di-white-transparent.png",
    diBlack: "/logos/di-black-transparent.png",
    diBlue: "/logos/logo-di-blue.png",
    plazaGrillos: "/logos/plaza-grillos-logo.png",
  },
  brands: {
    capitan: "/brands/capitan/capitan-gin.png",
    capitanDetail: "/brands/capitan/DSC_0127.jpg",
    capitanEtiquetaNegra: "/brands/capitan/DSC_0106.jpg",
    capitanLondonDry: "/brands/capitan/DSC_0129.jpg",
    capitanCork: "/brands/capitan/capitan-cork.jpg",
    capitanAwardGranOro: "/brands/capitan/awards/ASA_premio_oro.png",
    capitanAwardOroCopa: "/brands/capitan/awards/banner_premio_oro.png",
    capitanAwardPlata: "/brands/capitan/awards/ASA_premio_plata.png",
    etheryo: "/brands/etheryo/etheryo.png",
    refuerzo: "/brands/refuerzo/refuerzo.png",
    ribecky: "/brands/ribecky/ribecky.jpg",
    plazaGrillos: "/brands/pdg/bodega.png",
    plazaGrillosBottles: "/brands/pdg/CAP_03.png",
    plazaGrillosVideo: "/brands/pdg/pdg-vid.mp4",
  },
  store: {
    general: "/store/general/di_placa.png",
    capitanEtiquetaNegra: "/store/di/CapitanGin_ML_EtiquetaNegra.png",
    capitanEtiquetaNegraBack: "/store/di/CapitanGin_ML_EtiquetaNegra_back.png",
    capitanLondonDry: "/store/di/CapitanGin_ML_LondonDry.png",
    capitanLondonDryBack: "/store/di/CapitanGin_ML_LondonDry_back.png",
    pdgGranReserva: "/store/pdg/PlazaDeGrillos_ML_GranReserva.png",
    pdgGranReservaAlt: "/store/pdg/PlazaDeGrillos_ML_GranReserva_2.png",
    pdgIcono: "/store/pdg/PlazaDeGrillos_ML_Icono.png",
    pdgIconoAlt: "/store/pdg/PlazaDeGrillos_ML_Icono_2.png",
    pdgTheBlend: "/store/pdg/PlazaDeGrillos_ML_TheBlend.png",
    pdgTheBlendAlt: "/store/pdg/PlazaDeGrillos_ML_TheBlend_2.png",
  },
} as const
